import random
print("Kindly take less than 100!\n")
n = int(input("Enter the number:"))
print("Your entered number:",n)

m = random.randint(0,100)
print("Number generated by system:" , m)

if n<m:
    print("Your number is lower than number generated by system")
elif n>m:
    print("Your number is higher than number generated by system")
else:
    print("Your number is equal to number generated by system")

